spring:
  datasource:
    url: jdbc:h2:mem:meubanco;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: # vazio (default do H2)

  h2:
    console:
      enabled: true # ativa o console web do H2
      path: /h2-console # define o endpoint para acessar no navegador